# Generated by Django 6.0.1 on 2026-02-03 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbookimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flipbookimage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flipbookimage',
            name='is_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flipbookimage',
            name='is_front',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flipbookimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
