# Generated by Django 6.0.1 on 2026-02-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_images', '0002_flipbookimage_created_at_flipbookimage_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbookimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
