# Generated by Django 6.0.1 on 2026-02-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_images', '0003_alter_flipbookimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flipbookimage',
            name='is_back',
        ),
        migrations.RemoveField(
            model_name='flipbookimage',
            name='is_front',
        ),
        migrations.AlterField(
            model_name='flipbookimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
