# Generated by Django 6.0.1 on 2026-02-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_images', '0004_remove_flipbookimage_is_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbookimage',
            name='is_front',
            field=models.BooleanField(default=False),
        ),
    ]
